Add Recipient (person) and Recipient (organization)
kb-dk/ginnungagap pull request #33
Opened 2022-12-16 11:27 UTC by ernstnylan

2022-12-16 12:22 UTC, danege commented on src/main/resources/scripts/xslt/transformToMods.xsl
> +          </xsl:if>
Andet navn bør beholde den tidligere struktur med get_lang:
        <xsl:if test="field[@name='Andet navn']/value">
          <xsl:element name="mods:displayForm">
            <xsl:for-each select="field[@name='Andet navn']/value">
              <xsl:call-template name="cumulus_get_lang_attribute" />
              <xsl:call-template name="cumulus_get_value" />
            </xsl:for-each>
          </xsl:element>
        </xsl:if>

2022-12-16 12:23 UTC, danege commented on src/main/resources/scripts/xslt/transformToMods.xsl
> +          </xsl:if>
Samme som ovenstående med Andet navn

2022-12-16 12:23 UTC, danege commented on src/main/resources/scripts/xslt/transformToMods.xsl
> +          </xsl:if>
Samme som ovenstående med Andet navn

2022-12-16 12:24 UTC, danege requested changes
Se mine kommentarer om Andet navn

2022-12-16 13:18 UTC, danege approved these changes
Godkendt ;)

2022-12-20 11:10 UTC, rapi4321 approved these changes
Ser fint ud :)

2022-12-21 07:38 UTC, danege approved these changes
Godt!

2022-12-21 11:36 UTC, merged