Temporary files are saved in their own dir and deleted after return
kb-dk/ginnungagap pull request #34
Opened 2022-12-20 11:13 UTC by rapi4321

2022-12-20 13:18 UTC, ernstnylan approved these changes
Det ser fint ud :-)

2022-12-21 12:46 UTC, danege requested changes
Ser fint ud, se kommentar :)

2022-12-21 12:46 UTC, danege commented on src/main/java/dk/kb/ginnungagap/controller/MetadataController.java
> +
Det ville være fint, hvis denne metode blev lagt i FileUtils (og måske bruger Dir de steder, hvor der står tempDir

2022-12-21 13:13 UTC, rapi4321 commented on src/main/java/dk/kb/ginnungagap/controller/MetadataController.java
> +
Jeg har opdateret commit'et :)

2022-12-21 13:18 UTC, merged